import sqlite3
import argparse
import logging
import sys
from datetime import datetime

DB_PATH = "expenses.db"
LOG_PATH = "app.log"

# ---------------- LOGGING CONFIG ---------------- #
logging.basicConfig(
    filename=LOG_PATH,
    level=logging.INFO,
    format="%(asctime)s %(levelname)s: %(message)s"
)


# ---------------- DATABASE SETUP ---------------- #
def get_db():
    """Create database and table if not exists."""

    conn = sqlite3.connect(DB_PATH)

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS expenses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            date TEXT NOT NULL,
            description TEXT NOT NULL,
            amount REAL NOT NULL CHECK(amount > 0),
            category TEXT NOT NULL
        )
        """
    )

    return conn


# ---------------- ADD EXPENSE ---------------- #
def add_expense(desc, amount, category):
    try:
        amount = float(amount)

        if amount <= 0:
            raise ValueError("Amount must be greater than 0")

    except ValueError as e:
        print(f"❌ Invalid amount: {e}")
        logging.error(f"Invalid amount entered: {amount}")
        return

    category = category.strip().title()

    conn = get_db()

    with conn:
        conn.execute(
            """
            INSERT INTO expenses(date, description, amount, category)
            VALUES (?, ?, ?, ?)
            """,
            (
                datetime.now().strftime("%Y-%m-%d"),
                desc.strip(),
                amount,
                category
            )
        )

    conn.close()

    logging.info(f"ADD | {desc} | {amount} | {category}")

    print("✅ Expense added successfully!")


# ---------------- LIST EXPENSES ---------------- #
def list_expenses(month=None):

    conn = get_db()
    cur = conn.cursor()

    if month:
        rows = cur.execute(
            """
            SELECT id, date, description, amount, category
            FROM expenses
            WHERE substr(date,1,7)=?
            ORDER BY date DESC, id DESC
            """,
            (month,)
        ).fetchall()

    else:
        rows = cur.execute(
            """
            SELECT id, date, description, amount, category
            FROM expenses
            ORDER BY date DESC, id DESC
            """
        ).fetchall()

    conn.close()

    if not rows:
        print("⚠️ No expenses found.")
        return

    total = 0

    print("\nID   DATE         DESCRIPTION           AMOUNT     CATEGORY")
    print("-" * 65)

    for row in rows:
        print(f"{row[0]:<4} {row[1]:<12} {row[2]:<20} ₹{row[3]:<10.2f} {row[4]}")
        total += row[3]

    print("-" * 65)
    print(f"Total Expenses: ₹{total:.2f}")

    logging.info("LIST expenses")


# ---------------- REPORTS ---------------- #
def report(by):

    conn = get_db()
    cur = conn.cursor()

    if by == "category":

        query = """
        SELECT category, SUM(amount)
        FROM expenses
        GROUP BY category
        ORDER BY SUM(amount) DESC
        """

    elif by == "month":

        query = """
        SELECT substr(date,1,7), SUM(amount)
        FROM expenses
        GROUP BY substr(date,1,7)
        ORDER BY substr(date,1,7) DESC
        """

    else:
        print("❌ Use --by category OR --by month")
        return

    rows = cur.execute(query).fetchall()

    conn.close()

    if not rows:
        print("⚠️ No report data available.")
        return

    print("\n📊 REPORT")
    print("-" * 35)

    for key, total in rows:
        print(f"{key:<15} ₹{total:.2f}")

    logging.info(f"REPORT generated by {by}")


# ---------------- DELETE EXPENSE ---------------- #
def delete_expense(expense_id):

    conn = get_db()
    cur = conn.cursor()

    cur.execute(
        "DELETE FROM expenses WHERE id=?",
        (expense_id,)
    )

    conn.commit()
    conn.close()

    logging.info(f"DELETE expense id={expense_id}")

    print("🗑️ Expense deleted (if ID existed).")


# ---------------- CLI SETUP ---------------- #
def main():

    parser = argparse.ArgumentParser(
        description="Expense Tracker using SQLite"
    )

    sub = parser.add_subparsers(dest="cmd", required=True)


    # ADD COMMAND
    p_add = sub.add_parser("add", help="Add new expense")

    p_add.add_argument("--desc", required=True)
    p_add.add_argument("--amount", required=True)
    p_add.add_argument("--category", required=True)


    # LIST COMMAND
    p_list = sub.add_parser("list", help="List expenses")

    p_list.add_argument(
        "--month",
        help="Filter by YYYY-MM"
    )


    # REPORT COMMAND
    p_report = sub.add_parser("report", help="Generate reports")

    p_report.add_argument(
        "--by",
        choices=["category", "month"],
        required=True
    )


    # DELETE COMMAND
    p_delete = sub.add_parser("delete", help="Delete expense")

    p_delete.add_argument(
        "--id",
        type=int,
        required=True
    )


    args = parser.parse_args()


    try:

        if args.cmd == "add":
            add_expense(args.desc, args.amount, args.category)

        elif args.cmd == "list":
            list_expenses(args.month)

        elif args.cmd == "report":
            report(args.by)

        elif args.cmd == "delete":
            delete_expense(args.id)


    except Exception as e:

        logging.error(f"Unhandled error: {e}")

        print(f"❌ Error: {e}")

        sys.exit(1)


if __name__ == "__main__":
    main()